# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4242369a1e8b5d7e512d82356262da9"
name = "Breadcrumb"
application_url = "https://breadcrumb-shopify.web.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://breadcrumb-shopify.web.app/api/auth/shopify/callback"
]
